services:
  url_shortener_db:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
    volumes:
      - url-shortener-service-data:/var/lib/postgresql/data

  master_redis:
    image: redis/redis-stack:latest
    ports:
      - "6380:6379"

volumes:
  url-shortener-service-data: