CREATE SEQUENCE unique_number_seq
    START WITH 10000
    INCREMENT BY 1;

CREATE TABLE hash (
    id BIGSERIAL PRIMARY KEY,
    hash VARCHAR(7) NOT NULL UNIQUE
);

CREATE TABLE url (
    hash VARCHAR(7) PRIMARY KEY,
    url TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);