CREATE SEQUENCE unique_hash_number_sequence
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE hash (
                      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      actualHash VARCHAR(7) NOT NULL UNIQUE
);
CREATE TABLE urls (
                      id SERIAL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      long_url TEXT NOT NULL UNIQUE,
                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      hash VARCHAR(7) NOT NULL,
                      CONSTRAINT fk_hash FOREIGN KEY (hash) REFERENCES hash(actualHash)
);