CREATE TABLE IF NOT EXISTS hash (
    hash VARCHAR(6) NOT NULL,
    CONSTRAINT pk_hash PRIMARY KEY (hash)
);

CREATE TABLE IF NOT EXISTS url (
    hash VARCHAR(6) NOT NULL,
    url TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_url PRIMARY KEY (hash),
    CONSTRAINT fk_url_hash FOREIGN KEY (hash) REFERENCES hash (hash)
);

CREATE SEQUENCE IF NOT EXISTS unique_number_seq
    START WITH 1
    INCREMENT BY 1;