CREATE SEQUENCE unique_number_seq
    START WITH 100000
    INCREMENT BY 1;

CREATE TABLE url (
    hash VARCHAR(6) PRIMARY KEY,
    url VARCHAR(128) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE hash (
    hash VARCHAR(6) PRIMARY KEY
);