CREATE TABLE IF NOT EXISTS url(
    hash VARCHAR(6) PRIMARY KEY NOT NULL,
    url TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hash(
    hash VARCHAR(255) PRIMARY KEY NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS unique_hash_number_seq START WITH 1 INCREMENT BY 1;