CREATE TABLE IF NOT EXISTS url_urls
(
    hash VARCHAR(6) NOT NULL PRIMARY KEY,
    url VARCHAR(4096) NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS url_hashs
(
    hash VARCHAR(6) NOT NULL PRIMARY KEY
);

CREATE SEQUENCE IF NOT EXISTS url_unique_number_seq
    START 1
    INCREMENT 10;