CREATE SEQUENCE unique_hash_number_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS url
(
    hash       VARCHAR(6) PRIMARY KEY UNIQUE,
    url        VARCHAR(1048) NOT NULL,
    created_at TIMESTAMP     NOT NULL
);
CREATE INDEX idx_hash ON url (hash);

CREATE TABLE IF NOT EXISTS hash
(
    id   BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    hash VARCHAR(6) NOT NULL UNIQUE
);

