CREATE SEQUENCE unique_number_seq
START WITH 1
INCREMENT BY 1;

CREATE TABLE url(
hash VARCHAR(6) PRIMARY KEY NOT NULL,
url VARCHAR(4096) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE hash(
hash VARCHAR(6) NOT NULL);