CREATE TABLE hash
(
    hash VARCHAR(6) NOT NULL,
    CONSTRAINT pk_hash PRIMARY KEY (hash)
);

CREATE TABLE url
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hash       VARCHAR(6)                              NOT NULL,
    url        VARCHAR(100)                            NOT NULL,
    created_at timestamptz default current_timestamp,
    CONSTRAINT pk_url PRIMARY KEY (id)
);

ALTER TABLE url
    ADD CONSTRAINT uc_url_hash UNIQUE (hash);