CREATE TABLE IF NOT EXISTS url (
    hash VARCHAR(8) UNIQUE NOT NULL PRIMARY KEY,
    url VARCHAR(512) NOT NULL,
    last_get_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT current_timestamp
);

CREATE SEQUENCE IF NOT EXISTS unique_hash_number_seq
    START WITH 250000
    INCREMENT BY 7;

CREATE TABLE IF NOT EXISTS hash (
    hash VARCHAR(7) PRIMARY KEY
);