CREATE TABLE IF NOT EXISTS url(
    hash VARCHAR(6) PRIMARY KEY,
    url VARCHAR(512),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hash(
    hash VARCHAR(6) PRIMARY KEY
);

CREATE SEQUENCE IF NOT EXISTS unique_number_seq
    INCREMENT BY 1
    START WITH 1;

