CREATE TABLE IF NOT EXISTS url (
    hash VARCHAR(6) NOT NULL PRIMARY KEY,
    url VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS hash (
  hash VARCHAR(6) NOT NULL PRIMARY KEY
);

CREATE SEQUENCE IF NOT EXISTS hash_sequence
    START 56800235584
    INCREMENT 1;