CREATE TABLE IF NOT EXISTS urls (
    hash VARCHAR(6) PRIMARY KEY UNIQUE,
    url VARCHAR NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE IF NOT EXISTS hashes (
    hash VARCHAR(6) PRIMARY KEY UNIQUE,
);

CREATE SEQUENCE IF NOT EXISTS unique_number_seq
    START WITH 1
    INCREMENT BY 1;