CREATE TABLE IF NOT EXISTS url
(
    hash       VARCHAR(6)  NOT NULL PRIMARY KEY,
    url        VARCHAR     NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS hash
(
    hash VARCHAR(6) NOT NULL PRIMARY KEY
);

CREATE SEQUENCE IF NOT EXISTS hash_sequence
    START 916132832
    INCREMENT 1;