CREATE SEQUENCE IF NOT EXISTS unique_number_seq
    START 1
    INCREMENT 1;

CREATE TABLE IF NOT EXISTS hash (
    hash VARCHAR(6) PRIMARY KEY
    );

CREATE TABLE IF NOT EXISTS url (
    hash VARCHAR(6) PRIMARY KEY,
    url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_url_created_at ON url(created_at);