CREATE SEQUENCE unique_number_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE hash (
    id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    hash VARCHAR(255) NOT NULL
);

CREATE TABLE url (
    hash VARCHAR(6) PRIMARY KEY,
    url VARCHAR(256) NOT NULL
);