CREATE TABLE url(
hash VARCHAR(6) PRIMARY KEY,
url TEXT NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE hash(
hash VARCHAR(6) PRIMARY KEY
);

CREATE SEQUENCE unique_number_sequence
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE;

CREATE UNIQUE INDEX uq_url ON url(url);

