CREATE TABLE IF NOT EXISTs url
(
hash VARCHAR(6) PRIMARY KEY,
url VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFUALT CURRENT_TIMESTAMP,
);

CREATE TABLE IF NOT EXISTS hash
(
hash VARCHAR(6) PRIMARY KEY
);

CREATE SEQUENCE IF NOT EXISTS unique_number_seq
(
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOMAXVALUE
NOCYCLE
);