CREATE TABLE hash(
hash VARCHAR(6) PRIMARY KEY
);

CREATE TABLE url(
hash VARCHAR(6) PRIMARY KEY,
url VARCHAR(6) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
CONSTRAINT fk_url_hash FOREIGN KEY (hash) REFERENCES hash(hash)
);

CREATE SEQUENCE unique_number_seq
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 20;