CREATE TABLE url (
    hash VARCHAR(6) PRIMARY KEY,
    url TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hash (
    id BIGSERIAL NOT NULL,
    hash VARCHAR(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (hash)
);

CREATE SEQUENCE unique_number_seq
    START WITH 1
    INCREMENT BY 1;