CREATE TABLE IF NOT EXISTS url (
    hash VARCHAR(6) PRIMARY KEY NOT NULL,
    url VARCHAR NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hash (
    hash VARCHAR(6) PRIMARY KEY NOT NULL
);

CREATE SEQUENCE unique_number_seq
    START WITH 1
    INCREMENT BY 1;

