CREATE TABLE IF NOT EXISTS url(
    hash VARCHAR(6) PRIMARY KEY,
    url VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE hash(
    hash_value VARCHAR(6) PRIMARY KEY
);

CREATE SEQUENCE IF NOT EXISTS unique_numbers_seq INCREMENT BY 1 MINVALUE 1 START 1;