CREATE TABLE hash(
hash VARCHAR (6) PRIMARY KEY
);

CREATE TABLE url(
hash VARCHAR (6) PRIMARY KEY UNIQUE,
url VARCHAR NOT NULL,
created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE unique_number_seq INCREMENT BY 1 START WITH 1;