CREATE SEQUENCE unique_hash_number_seq START WITH 238328 INCREMENT BY 83;

CREATE TABLE hash (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    hash VARCHAR(8) NOT NULL UNIQUE
);

CREATE TABLE url (
    hash VARCHAR(8) PRIMARY KEY,
    url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ DEFAULT NOW() + INTERVAL '6 months'
)