CREATE TABLE IF NOT EXISTS url (
    hash VARCHAR(6) PRIMARY KEY,
    url TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_url_url ON url (url);
CREATE INDEX IF NOT EXISTS idx_url_created_at ON url (created_at);

CREATE TABLE IF NOT EXISTS hash (
    hash VARCHAR(6) PRIMARY KEY
);

CREATE SEQUENCE IF NOT EXISTS unique_number_seq
    START WITH 916132832
    INCREMENT BY 1
;