CREATE SEQUENCE unique_hash_number_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE hash (
    hash VARCHAR(6) NOT NULL PRIMARY KEY UNIQUE
);

CREATE TABLE url (
    hash VARCHAR(6) NOT NULL PRIMARY KEY UNIQUE,
    url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);