CREATE TABLE IF NOT EXISTS url
(
    hash        VARCHAR(6) PRIMARY KEY,
    url         VARCHAR(4096) NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hash
(
    hash        VARCHAR(6) PRIMARY KEY
);

CREATE SEQUENCE IF NOT EXISTS unuqie_number_seq
START WITH 1
INCREMENT BY 1;