CREATE TABLE IF NOT EXISTS url (
    hash VARCHAR(6) NOT NULL,
    url VARCHAR(2083) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_url PRIMARY KEY (hash)
);

CREATE TABLE IF NOT EXISTS hash (
    hash VARCHAR(6) NOT NULL,
    CONSTRAINT pk_hash PRIMARY KEY (hash)
);

CREATE SEQUENCE IF NOT EXISTS unique_number_seq
    START WITH 1
    INCREMENT BY 1