CREATE TABLE hashes
(
    hash VARCHAR(6) NOT NULL PRIMARY KEY
);

CREATE TABLE url
(
    hash       VARCHAR(6) NOT NULL PRIMARY KEY ,
    url        VARCHAR    NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE unique_number_sequence
START WITH 1
INCREMENT BY 1;
