CREATE TABLE IF NOT EXISTS hash (
    id         BIGINT       PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE ,
    hash       VARCHAR(7)   NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS url (
    id         bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    hash       VARCHAR(7)  UNIQUE NOT NULL,
    url        VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_url_hash ON url(hash);

CREATE SEQUENCE IF NOT EXISTS unique_number_seq
     AS bigint
     INCREMENT  BY   1
     START      WITH 1