CREATE TABLE hash
(
    id   BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    hash VARCHAR(6) UNIQUE
);

CREATE TABLE url
(
    id         BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    hash       VARCHAR(6) UNIQUE,
    url        VARCHAR(2048) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,


    CONSTRAINT fk_hash FOREIGN KEY (hash) REFERENCES hash (id)


);

CREATE SEQUENCE unique_number_seq
    START WITH 1
    INCREMENT BY 1;