CREATE TABLE url
(
    id             BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    hash           VARCHAR(6) UNIQUE ,
    url            TEXT NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hash
(
    id             BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    hash           VARCHAR(6) UNIQUE
);
CREATE SEQUENCE unique_number_seq
    INCREMENT BY 1
    START WITH 1
