CREATE SEQUENCE IF NOT EXISTS unique_number_seq
    INCREMENT BY 10
    START WITH 1;

CREATE TABLE IF NOT EXISTS url
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url        varchar(2048)                       NOT NULL,
    hash       VARCHAR(6)                          NOT NULL UNIQUE,
    created_at timestamp DEFAULT current_timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS hash
(
    id   BIGINT PRIMARY KEY DEFAULT nextval('unique_number_seq'),
    hash VARCHAR(6) NOT NULL UNIQUE
);