CREATE TABLE IF NOT EXISTS hash (
    hash VARCHAR(6) PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS url (
    hash VARCHAR(6) PRIMARY KEY NOT NULL,
    url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE SEQUENCE IF NOT EXISTS unique_number_seq
    START WITH 1
    INCREMENT BY 1;
