CREATE TABLE IF NOT EXISTS url
(
    hash        VARCHAR(6)  PRIMARY KEY,
    url         VARCHAR     NOT NULL
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
    expired_at  TIMESTAMP   NOT NULL
);

CREATE TABLE IF NOT EXISTS hash
(
    hash VARCHAR(6) PRIMARY KEY
    CONSTRAINT hash_length CHECK (length(hash) = 6)
);

CREATE SEQUENCE unique_int_seq
    START WITH 916312072
    INCREMENT BY 1;
