CREATE SEQUENCE unique_number_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE hashes (
    hash VARCHAR(6) PRIMARY KEY NOT NULL
);

CREATE TABLE urls (
    hash VARCHAR(6) PRIMARY KEY NOT NULL,
    url VARCHAR(4096) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
