CREATE SEQUENCE unique_number_seq START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE;

CREATE TABLE url (
    hash VARCHAR(20) PRIMARY KEY not null UNIQUE,
    url VARCHAR(255) NOT NULL UNIQUE,
    created_at timestamptz DEFAULT current_timestamp,
);

CREATE TABLE hash (
    hash VARCHAR(20) PRIMARY KEY NOT NULL UNIQUE,
);