CREATE SEQUENCE  unique_hash_number_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE url (
    hash VARCHAR(6) PRIMARY KEY,
    url  TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE hash (
    hash VARCHAR(6) PRIMARY KEY
);

CREATE INDEX url_hash_idx ON url(url);
