CREATE TABLE IF NOT EXISTS url (
  hash VARCHAR(6) PRIMARY KEY,
  url TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hash (
  id BIGINT PRIMARY KEY,
  hash VARCHAR(6)
);

CREATE SEQUENCE unique_number_seq
  START WITH 1
  INCREMENT BY 1;
