CREATE TABLE url (
    id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    hash CHAR(6) UNIQUE NOT NULL ,
    url TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT current_timestamp NOT NULL
);

CREATE TABLE hash (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    hash CHAR(6) UNIQUE
);

CREATE SEQUENCE unique_number_seq
    START WITH 1
    INCREMENT BY 1