CREATE TABLE IF NOT EXISTS url (
  hash VARCHAR(6) PRIMARY KEY,
  url TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hash(
hash VARCHAR(7)PRIMARY KEY
);

CREATE SEQUENCE unique_hash_number_seq
START WITH 1
INCREMENT BY 1;