CREATE TABLE hash (
    id BIGINT PRIMARY KEY,
    hash VARCHAR(8) NOT NULL UNIQUE
);

CREATE TABLE url (
    hash_id BIGINT NOT NULL UNIQUE REFERENCES hash(id),
    url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE unique_number_seq START 10000;
