CREATE TABLE hash (
    hash VARCHAR(8) PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    CONSTRAINT fk_hash_url FOREIGN KEY (hash) REFERENCES url (hash)
);

CREATE TABLE url (
    hash VARCHAR(8) PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    url VARCHAR(128),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE unique_number_seq
    START WITH 1
    INCREMENT BY 1;