CREATE SEQUENCE unique_number_seq START 1;

CREATE TABLE hash (
    hash VARCHAR(8) PRIMARY KEY NOT NULL
);

CREATE TABLE url (
    hash VARCHAR(8) PRIMARY KEY,
    url VARCHAR(1024) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);