CREATE SEQUENCE IF NOT EXISTS unique_hash_number_seq
    START WITH 916132832
    INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS url (
    hash VARCHAR(7) PRIMARY KEY,
    url TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS hash (
    hash VARCHAR(6) PRIMARY KEY
);
