CREATE SEQUENCE IF NOT EXISTS unique_number_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS hash (
    hash VARCHAR(6) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS url (
    hash VARCHAR(6) PRIMARY KEY,
    url TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_url_hash FOREIGN KEY (hash) REFERENCES hash(hash)
);