CREATE TABLE IF NOT EXISTS hash (
    hash VARCHAR(6) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS url
(
    hash            VARCHAR(6) PRIMARY KEY,
    url             VARCHAR,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_hash FOREIGN KEY (hash) REFERENCES hash (hash)
);

CREATE SEQUENCE unique_numbers_seq START WITH 1 INCREMENT BY 1;