name: Url Shortener Service CI pipeline for Yom

on:
  pull_request:
    branches:
      - Yom-master-stream9

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v3

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Step 3 - Set gradlew executable
        run: chmod +x gradlew

      - name: Step 4 - Cache dependencies on Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/cache
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Step 5 - Build project with Gradle
        run: ./gradlew build

      - name: Step 6 - Run tests with Gradle
        run: ./gradlew clean test
